### ISSUE TITLE
Enhance C/C++ language services in ARTIK IDE

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik-ide#225]
The current support for C/C++ in the ARTIK IDE covers syntax highlighting but developers have requested richer support.

The open [language server protocol](https://github.com/Microsoft/language-server-protocol) offers a clean way to plug C/C++ language intellisense into the ARTIK IDE via an Eclipse Che plugin. However, there is currently no C/C++ language server available. More information on the LSP can be seen in these CheConf 2016 presentations:
[LSP overview](https://eclipse.org/che/checonf/sessions.html#quinn)
[Extending language support in Che](https://eclipse.org/che/checonf/sessions.html#stevan) 

This epic outlines what would need to be done to create a language server protocol for C/C++.

- [ ] Create a C/C++ language server plugin for Eclipse Che
   - [ ] Enable syntax highlighting for C and C++ files
   - [ ] Add code completion for C and C++ files
   - [ ] Add syntax validation for C and C++ files
- [ ] Enable C/C++ language server agents for all C/C++ and ARTIK stacks
- [ ] Update ARTIK getting started guide in docs to point users toward new intellisense features
